### PR TITLE
Catalan language to whoBIRD app

### PR DESCRIPTION
**Pull request by mrestivill**
Hi,
I've added a new translation to catalan language, I've don't know if there is some other files to be modified to be able to work.

Thanks

Marc

### CODE REVIEW

**Comment by woheller69** [comment]
that does not sound very Canadian...

**Comment by woheller69** [comment]
maybe it should be values-es-rCA ?

**Comment by Dimas-sc** [comment]
As you can see, 'ca' is Catalan

https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes
https://www.loc.gov/standards/iso639-2/langhome.html
https://www.andiamo.co.uk/resources/iso-language-codes/

**Comment by mrestivill** [comment]
This file labels_ca.txt cames from https://github.com/mcguirepr89/BirdNET-Pi?tab=readme-ov-file#internationalization this other repo, It's inside a zip file https://github.com/mcguirepr89/BirdNET-Pi/tree/main/model

**Comment by mrestivill** [comment]
Sorry I didn't mention the catalan language. i've updated the PR title.

**Comment by woheller69** [comment]
labels_ca does not have the correct length. It needs 6522 lines.
So it is for an older BirdNET version.

**Comment by mrestivill** [comment]
Updated file

**Comment by woheller69** [comment]
```notfound``` is not a good solution. I would suggest to replace these at least with the English or Spanish name

**Comment by mrestivill** [comment]
Fixed notfound with spanish or english words.

**Comment by woheller69** [comment]
thanks, great. Will merge soon.

**Pull request merged**
