### PR TITLE
Add drawable to show record/pause function and add tooltips

### PR DESCRIPTION
**Pull request by SIRSteiner**
Referred to #27 , #28 and #33
I solved this for you because you have no intention of solving this problem.

### CODE REVIEW

**Comment by woheller69** [comment]
we can add the play/pause button, but I will not add tooltips

**Comment by SIRSteiner** [comment]
Some find tooltips  useful some not. IMHO it is a small thing which don't bloat the app. But you are the developer - you can merge both commits or only one...

**Comment by woheller69** [comment]
Done, without tooltips

**Comment by seniordevel** [comment]
Thank you for adding seperate play pause buttons.

**Pull request closed without merging**
